service: uassign-api

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: dev
    DOMAIN_SUFFIX: space

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

package:
  include:
    - .env

functions:
  addNote:
    handler: app/handler.addNote
    events:
      - http:
          path: notes
          method: post
          cors: true
  updateNote:
    handler: app/handler.updateNote
    events:
      - http:
          path: notes/{id}
          method: put
          cors: true
  deleteNote:
    handler: app/handler.deleteNote
    events:
      - http:
          path: notes/{id}
          method: delete
          cors: true
  getNote:
    handler: app/handler.getNote
    events:
      - http:
          path: notes/{id}
          method: get
          cors: true
  getAllNotes:
    handler: app/handler.getAllNotes
    events:
      - http:
          path: notes
          method: get
          cors: true
  getUser:
    handler: app/handlers/user.get 
    events:
      - http:
          path: user
          method: post
          cors: true
  getAllUsers:
    handler: app/handlers/user.getAll 
    events:
      - http:
          path: user
          method: get
          cors: true
  getMe:
    handler: app/handlers/user.me 
    events:
      - http:
          path: user/me
          method: get
          cors: true
  updateMe:
    handler: app/handlers/user.updateMe 
    events:
      - http:
          path: user/me
          method: patch
          cors: true
  addAdmin:
    handler: app/handlers/user.addAdmin 
    events:
      - http:
          path: user/admin
          method: post
          cors: true
  removeAdmin:
    handler: app/handlers/user.removeAdmin 
    events:
      - http:
          path: user/admin
          method: delete
          cors: true
  addProf:
    handler: app/handlers/user.addProf 
    events:
      - http:
          path: user/prof
          method: post
          cors: true
  removeProf:
    handler: app/handlers/user.removeProf 
    events:
      - http:
          path: user/prof
          method: delete
          cors: true
  addFile:
    handler: app/handler.addFile
    events:
      - http:
          path: files
          method: post
          cors: true
  getFile:
    handler: app/handler.getFile
    events:
      - http:
          path: files/{uuid}
          method: get
          cors: true
  deleteFile:
    handler: app/handler.deleteFile
    events:
      - http:
          path: files/{id}
          method: delete
          cors: true

resources:
  Resources:
    serviceUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: service-user-pool-${opt:stage, self:provider.stage}
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    serviceUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: service-user-pool-client-${opt:stage, self:provider.stage}
        AllowedOAuthFlows:
          - implicit
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthScopes:
          - phone
          - email
          - openid
          - profile
          - aws.cognito.signin.user.admin
        UserPoolId:
          Ref: serviceUserPool
        CallbackURLs: 
          - https://localhost:3000
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        GenerateSecret: false
        SupportedIdentityProviders: 
          - COGNITO
    serviceUserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain 
      Properties:
        UserPoolId: 
          Ref: serviceUserPool
        Domain: service-user-pool-domain-${opt:stage, self:provider.stage}-${self:provider.environment.DOMAIN_SUFFIX}
