service: uassign-api

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    NODE_ENV: dev
    DOMAIN_SUFFIX: space

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

package:
  include:
    - .env

functions:
  addNote:
    handler: app/handler.addNote
    events:
      - http:
          path: notes
          method: post
  updateNote:
    handler: app/handler.updateNote
    events:
      - http:
          path: notes/{id}
          method: put
  deleteNote:
    handler: app/handler.deleteNote
    events:
      - http:
          path: notes/{id}
          method: delete
  getNote:
    handler: app/handler.getNote
    events:
      - http:
          path: notes/{id}
          method: get
  getAllNotes:
    handler: app/handler.getAllNotes
    events:
      - http:
          path: notes
          method: get
  getUser:
    handler: app/handlers/user.get 
    events:
      - http:
          path: user
          method: get
  addAdmin:
    handler: app/handlers/user.addAdmin
    events:
      - http:
        path: user/admin
        method: post
  removeAdmin:
    handler: app/handlers/user.removeAdmin
    events:
      - http:
        path: user/admin 
        method: delete

resources:
  Resources:
    serviceUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: service-user-pool-${opt:stage, self:provider.stage}
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
    serviceUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: service-user-pool-client-${opt:stage, self:provider.stage}
        AllowedOAuthFlows:
          - implicit
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthScopes:
          - phone
          - email
          - openid
          - profile
          - aws.cognito.signin.user.admin
        UserPoolId:
          Ref: serviceUserPool
        CallbackURLs: 
          - https://localhost:3000
        ExplicitAuthFlows:
          - ALLOW_USER_SRP_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        GenerateSecret: false
        SupportedIdentityProviders: 
          - COGNITO
    serviceUserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain 
      Properties:
        UserPoolId: 
          Ref: serviceUserPool
        Domain: service-user-pool-domain-${opt:stage, self:provider.stage}-${self:provider.environment.DOMAIN_SUFFIX}