name: Run Unit Tests for Frontend
on:
  pull_request:
    branches:
      - dev
    paths:
      - 'frontend/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd frontend
          npm i
          npm run test
