name: Deploy AWS Lambda

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: configure .env
      run: |
        cd lambda
        touch .env 
        echo "DB=${{ secrets.DB_DEV }}" > .env
        npm install -g serverless
        serverless config credentials --provider aws --key ${{ secrets.KIAUELLLUXG3R4ADV7A }} --secret ${{ secrets.MoGVN8pOErJ1hCmHJIFdBHXajgnLsk0CtSmMKbuY }}
        serverless deploy
